services:
  crazysim:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: remote_pc_humble

    network_mode: "host"
    ipc: "host"
    privileged: true

    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - HOST_UID=${HOST_UID:-1000}
      - LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/usr/lib/wsl/lib
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-/mnt/wslg/runtime-dir}

    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /mnt/wslg:/mnt/wslg:rw
      - /usr/lib/wsl:/usr/lib/wsl:ro
      - ${HOME}/crazyflie_docker/my_code:/root/my_code

    devices:
      - /dev/dxg:/dev/dxg

    command: tail -f /dev/null
